name: Feature Request
description: Suggest a new feature or improvement for Jollycat
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        We'd love to hear your ideas for making Jollycat better!
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear description of what you'd like to see added or changed.
      placeholder: I'd like Jollycat to...
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use case or pain point this feature would address.
      placeholder: Currently I have to...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
      description: Any workarounds or alternative solutions you've tried.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Screenshots, mockups, links, or any other context.
    validations:
      required: false
